# generated by Claude - Sonnet 4.6
import logging
from src.aas_agent_config import AgentConfig
from src.core.event_listener import EventListener

logging.basicConfig(
    level=logging.DEBUG,
    format="%(asctime)s [%(levelname)-8s] %(name)s — %(message)s",
    datefmt="%H:%M:%S",
)

# Testet die MQTT-Verbindung und das Empfangs-Callback mit einem Dummy-Handler.


def dummy_handler(topic: str, payload: str) -> None:
    print(f"Topic: {topic}")
    print(f"Payload: {payload}")

config = AgentConfig()
listener = EventListener(config.mqtt, on_message=dummy_handler)
listener.start()

input("Drücke Enter zum Beenden...\n")
listener.stop()