# generated by Claude - Sonnet 4.6
import logging
from aas_agent.config import AgentConfig
from aas_agent.aas_operation_service import AasOperationService
from aas_agent.event_listener import EventListener
from aas_agent.event_handler import EventHandler

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s.%(msecs)03d [%(levelname)-8s] %(name)s — %(message)s",
    datefmt="%H:%M:%S"
)
# testet die EventHandler-Logik und einfachen AAS-Operationen mit realen Mqtt-Nachrichten

config = AgentConfig()
service = AasOperationService(config.aas)
handler = EventHandler(service)
listener = EventListener(config.mqtt, on_message=handler.handle)
listener.start()

print("Warte auf MQTT-Nachrichten...")

input("Drücke Enter zum Beenden...\n")
listener.stop()
