# generated by Claude - Sonnet 4.6
import logging
from aas_agent.aas_agent_config import AgentConfig
from aas_agent.core.event_listener import EventListener
from aas_agent.core.event_handler import EventHandler

logging.basicConfig(
    level=logging.WARNING,
    format="%(asctime)s [%(levelname)-8s] %(name)s — %(message)s",
    datefmt="%H:%M:%S",
)
# testet die EventHandler-Logik mit realen MQTT-Nachrichten (ohne echten AAS-Service)

class MockAasOperationService:
    def __getattr__(self, name):
        def mock_method(*args, **kwargs):
            print(f"[MOCK] Funktion aufgerufen: {name}({', '.join(repr(a) for a in args)}{', '.join(f'{k}={v!r}' for k, v in kwargs.items())})")
        return mock_method

config = AgentConfig()
service = MockAasOperationService()
handler = EventHandler(service)
listener = EventListener(config.mqtt, on_message=handler.handle)
listener.start()

print("Warte auf MQTT-Nachrichten...")
print()

input("Drücke Enter zum Beenden...\n")
listener.stop()